### ISSUE TITLE
THE MOODLE UPDATE

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/elearning-moodle#1]
## Todo

- [x] Set up a staging server (staging.nonproliferation-elearning.eu)
- [x] Make a staging database and sync it with production
- [x] Copy moodle files to staging
- [x] Install Moodle locally so we can:
  - [x] Sync the local database with staging (via SQL dump)
  - [x] TBD run the Moodle update (See https://docs.moodle.org/402/en/Upgrading)
  - [x] Version-control the updated theme (see https://github.com/Peace-Research-Institute-Frankfurt/elearning-moodle)
  - [x] #2
  - [x] #9 
- [x] Run the update on staging (see process below)
- [x] **June 23**: Put up a notice on production to warn people about the downtime (Looks like "Site announcement" will work ok for this, see copy below)
- [x] **June 30**: Run the update on production

## Upgrade process

- [x] **Preparation**
  - [x] Make a new folder called `/moodle-3.9` on the server
  - [x] Upload Moodle 3.9 to `/moodle-3.9`
  - [x] Make a new folder called `/moodle-4.1` on the server
  - [x] Upload Moodle 4.1[^2] to `/moodle-4.1`
  - [x] Copy the following from the production folder to `/moodle-3.5 ` and `/moodle-4.1`:
    - [x] `config.php`
    - [x] `theme/hsfk` (3.5 only)
    - [x] `theme/bootstrapbase`
    - [x] `mod/certificate`
    - [x] `enrol/auto`
    - [x] `.htaccess`
    - [x] `.htpasswd`
  - [x] Change `$CFG->dbtype` from `mysql` to `mariadb` in `config.php`.
  - [x] Upload a `.user.ini` file setting `max_input_vars=5000` to `/moodle-4.1`
  - [x] Upload the rebuilt theme (this repo) to `/moodle-4.1/theme`
  - [x] Copy `/learningunits` to `moodle-4.1`
  - [x] Copy `/matomo` to `moodle-4.1`
  - [x] Back up the production database
- [x] **Moodle to 3.9**
  - [x] Rename the production folder to `/production-old`
  - [x] Rename `/moodle-3.9` to `/nonproliferation-elearning.eu`
  - [x] Load up the Moodle admin and follow instructions to update the database
  - [x] Update PHP from 7.2 to 7.4 in KAS [^3]
- [x] **Moodle to 4.1**
  - [x] Rename the production folder to `/production-3.9`
  - [x] Rename `/moodle-4.1` to `/nonproliferation-elearning.eu`
  - [x] Load up the Moodle admin and follow instructions to update the database
  - [x] Update PHP from 7.4 to 8.0 in KAS
- [x] **Content updates**
  - [x] Remove year from copyright setting
  - [x] Upload header image
  - [x] Add a "Course Custom Field" called `lu_authors`
  - [x] Move author names from course description to `lu_authors`
  - [x] Replace `mod_certificate` with [`mod_customcert@3.1`](https://moodle.org/plugins/mod_customcert/versions) (former is unmaintained)
    - [x] Install the plugin from zip
    - [x] Add two instances of it to the certificate course
    - [x] Configure restriction settings (the same as the current certificate plugin)
    - [x] Set certificate template (see below)
    - [x] Remove current certificate blocks
  - [x] Remove update warning

We'll do this three times:

- [x] Dev
- [x] Staging
- [x] Production 

I think Moodle will migrate the database during the upgrade, so we probably won't have to touch production manually. `moodledata` can also stay in place.

## Announcement draft copy

Scheduled maintenance: Our website will be unavailable from approximately 10am to 2pm on Friday, June 24th, 2023 for scheduled software updates. Our certificate section and other site functions may be intermittently available as we work through the transition. All services will resume regular operation by Monday, June 28. If you have questions, please contact info@nonproliferation-elearning.eu.

## Certificate Template
| Type         | Copy                                                                                                                                                              | X   | Y   | Size | Font           | Color   |
| ------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------- | --- | --- | ---- | -------------- | ------- |
| Text         | The EU Non-Proliferation and Disarmament Consortium hereby certifies that                                                                                         | 105 | 46  | 12   | Helvetica      | #000    |
| Student Name | [Student Name]                                                                                                                                                    | 105 | 63  | 26   | Helvetica      | #000    |
| Text         | was awarded the                                                                                                                                                   | 105 | 80  | 12   | Helvetica      | #000    |
| Text         | Basic Certificate                                                                                                                                                 | 105 | 91  | 26   | Helvetica Bold | #0c425b |
| Text         | having completed the following learning units of the EU Non-Proliferation and Disarmament Consortium eLearning course available at nonproliferation-elearning.eu: | 105 | 112 | 12   | Helvetica      | #000    |
| Text         | [List of Units]                                                                                                                                                   | 105 | 145 | 10   | Helvetica      | #000    |
| Date         | [Issue Date]                                                                                                                                                      | 105 | 206 | 12   | Helvetica      | #000    |
| Code         | [Code]                                                                                                                                                            | 15  | 284 | 7    | Courier        | #000    |

[^2]: The latest version is 4.2, but that [requires MariaDB@^10.6.7](https://moodledev.io/general/releases/4.2#database-requirements), which isn't supported by our hosting company or our dev environment (see https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2623)
[^3]: We can't update to PHP 8 at this stage, see https://docs.moodle.org/dev/Moodle_and_PHP
