### ISSUE TITLE
Update the theme

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/elearning-moodle#2]
## Todo
- [x] Replace custom UI components with Bootstrap 4 interactions or plain JS where possible
  - [x] Rewrite header video interaction in plain JS
- [x] Update dependencies, replace deprecated moodle functions
- [x] Migrate to Roboto Flex
- [x] Move all templating to mustache, see https://docs.moodle.org/dev/Themes_overview#Layout_files
  - [x] Move `home`
  - [x] Move `course`
  - [x] Move `incourse`
  - [x] Move `course_renderer`
- [x] Fix the most obvious A11y problems
  - [x] Ensure the site is keyboard-usable
  - [x] Fix contrast issues
- [x] ~~Import Javascript files via amd (but don't use grunt to compile it, we're not in 2012)~~ Looks like it takes a very specific Grunt/Node 17/custom Babel plugin workflow to compile Javascript to the format Moodle expects; we will not be doing that.
- [x] Make sure the header video is served by our video streaming service, not the origin server
  - [x] ~~Re-upload video to our streaming provider~~ Already there, just had to use it.
- [x] Rewrite unit/author merge in a more elegant way (ideally we'll avoid string-matching in Javascript)
  - [x] Add a custom field to courses that holds a semicolon-separated list of author names which we'll then match against `contributors`
- [x] Replace logo with SVG
- [x] Fix search results view
- [x] Fix narrow views
  - [x] Restore collapsible navbar, see: https://getbootstrap.com/docs/4.0/components/navbar/
- [x] Remove unused files
