### ISSUE TITLE
Set up continuous delivery for the theme to staging and production

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/elearning-moodle#3]
We want to:

- Protect `main`
- Have a `develop` branch that deploys to staging
- Have `main` deploy to production whenever a pull request is merged

## Todo

- [x] Set up FTP user `gh-actions-staging` on KAS
- [x] Set up FTP user `gh-actions-prod` on KAS
- [x] Add FTP users as repo secrets
- [x] Build the deploy action for staging (runs on `pull_request`)
  - [x] Deploy the theme via FTP
  - [ ] [Log in via SSH](https://blog.benoitblanchon.fr/github-action-run-ssh-commands/) to [purge the caches](https://docs.moodle.org/402/en/Administration_via_command_line#Purge_caches)
- [ ] Build the deploy action for production (runs on commit to `main`)

## Notes

- https://moodle.org/mod/forum/discuss.php?d=355057

**Comment by awesomephant** [comment]
Not seeing a way to do step 2 that doesn't involve a lot of technical debt, closing as half-done for now.
