### ISSUE TITLE
Move Matomo to a subdomain

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/elearning-moodle#7]
Blocked by #1.

Running Matomo analytics next to Moodle makes it harder to update Moodle because we have to manually copy `/matomo` across every time. It also forces both packages to use the same dependencies (like PHP and MariaDB), which might create problems in the future.

The better approach would be to move all the Matomo code to a subdomain like `analytics.nonproliferation-elearning.com`, where it can be maintained independetly.

See:
- https://matomo.org/faq/how-to-install/faq_18/
- https://github.com/matomo-org/matomo/issues/16707

## Todo

- [x] Create a subdomain called `analytics.nonproliferation-elearning.com` in KAS
- [x] move all your Matomo files to the new directory, on your new domain or subdomain.
- [x] in your `config/config.ini.php` file, below [General] section, add a line with your new host: trusted_hosts[] = "example-stats.net"
- [x] delete the folder tmp/ within your new Matomo directory.
- [x] open the new Matomo URL in your browser, and check that Matomo works as expected.
- [x] since the Matomo (Piwik) domain name has changed, you also need to change the Matomo [JavaScript tags](http://developer.matomo.org/guides/tracking-javascript-guide) on all your tracked pages. For example, if Matomo was installed in matomo.example.org and is now installed in example-stats.net, you need to update the tags on all your websites’ pages to point to the new URL. Done in 648be2d6c16140b6c55dc1382a41f6dfd1058447
