### ISSUE TITLE
Move learning unit content to a subdomain

### ISSUE THREAD

**Issue by awesomephant** [Peace-Research-Institute-Frankfurt/elearning-moodle#8]
Blocked by #1 

Keeping learning unit files (Lernbar) next to Moodle makes it harder to update Moodle because we have to manually copy `/learningunits` across every time. It also forces both packages to use the same dependencies (like PHP and MariaDB), which might create problems in the future.

The better approach would be to move all the Matomo code to a subdomain like `lu.nonproliferation-elearning.com`, where it can be maintained independetly.

## Todo

- [x] Create a new subdomain at `lu.nonproliferation-elearning.eu`
- [x] Downlaod all existing learning unit files
- [x] Upload all learning unit files to the new subdomain
- [ ] Update `.htaccess` to 302 redirect all existing links to the new subdomain
- [ ] Update the custom menu in Moodle to point directly to the new subdomain

**Comment by awesomephant** [comment]
Would screw our analytics, closing for now.
